# Generated by Django 5.0.4 on 2024-04-18 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Modified', models.DateTimeField(auto_now=True)),
                ('Title', models.CharField(max_length=200, verbose_name='')),
                ('Text', models.TextField(verbose_name='')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Modified', models.DateTimeField(auto_now=True)),
                ('Name', models.CharField(max_length=100, verbose_name='')),
                ('Phone', models.CharField(max_length=13, verbose_name='')),
                ('Password', models.CharField(max_length=50, verbose_name='')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Modified', models.DateTimeField(auto_now=True)),
                ('Text', models.TextField(verbose_name='')),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_cm', to='user.post', verbose_name='Post')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cm', to='user.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'PostComment',
                'verbose_name_plural': 'PostComments',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_post', to='user.user', verbose_name='User'),
        ),
    ]
