# Generated by Django 5.0.4 on 2024-04-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Image',
            field=models.ImageField(default=0, upload_to='Post/', verbose_name=''),
            preserve_default=False,
        ),
    ]
